/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.14 and the Signal Processing Toolbox 6.17.
 *
 * Generated on: 18-Jan-2016 16:30:05
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 61
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
// #include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2012a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
// const int LPL = 61;
#define LPL 61
// const int16_T LP[61] = {
const Int16 LP[61] = {
       -5,     15,     16,    -15,    -35,      9,     64,     16,    -92,
      -69,    105,    150,    -81,   -251,     -1,    349,    161,   -406,
     -405,    369,    723,   -177,  -1086,   -255,   1449,   1082,  -1761,
    -2820,   1971,  10202,  14339,  10202,   1971,  -2820,  -1761,   1082,
     1449,   -255,  -1086,   -177,    723,    369,   -405,   -406,    161,
      349,     -1,   -251,    -81,    150,    105,    -69,    -92,     16,
       64,      9,    -35,    -15,     16,     15,     -5
};